services:
  booking_service:
    build: ..\booking_service
    ports:
      - "8080:8080"
  room_service:
    build: ..\room_service
    ports:
      - "8081:8081"
  user_service:
    build: ..\user_service
    ports:
      - "8082:8082"
  booking_gateway:
    build: ..\booking-gateway
    ports:
      - "9090:9090"
  eureka-server:
    build: ..\eureka_server
    ports:
      - "8761:8761"